CREATE TABLE IF NOT EXISTS user_role (
    id SERIAL PRIMARY KEY,
    role_id BIGINT NOT NULL REFRENCES roles(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFRENCES users(id) ON DELETE CASCADE,
   
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL
);